/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPartsRouteRouteImport } from './routes/_authenticated/parts/route'
import { Route as AuthenticatedInspectionsRouteRouteImport } from './routes/_authenticated/inspections/route'
import { Route as AuthenticatedExpensesRouteRouteImport } from './routes/_authenticated/expenses/route'
import { Route as AuthenticatedCompaniesRouteRouteImport } from './routes/_authenticated/companies/route'
import { Route as AuthenticatedCarsRouteRouteImport } from './routes/_authenticated/cars/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedPartsIndexRouteImport } from './routes/_authenticated/parts/index'
import { Route as AuthenticatedInspectionsIndexRouteImport } from './routes/_authenticated/inspections/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedExpensesIndexRouteImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated/cars/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPartsNewRouteImport } from './routes/_authenticated/parts/new'
import { Route as AuthenticatedInspectionsNewRouteImport } from './routes/_authenticated/inspections/new'
import { Route as AuthenticatedExpensesNewRouteImport } from './routes/_authenticated/expenses/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCompaniesNewRouteImport } from './routes/_authenticated/companies/new'
import { Route as AuthenticatedCarsNewRouteImport } from './routes/_authenticated/cars/new'
import { Route as AuthenticatedPartsPartIdRouteRouteImport } from './routes/_authenticated/parts/$partId/route'
import { Route as AuthenticatedInspectionsInspectionIdRouteRouteImport } from './routes/_authenticated/inspections/$inspectionId/route'
import { Route as AuthenticatedExpensesExpenseIdRouteRouteImport } from './routes/_authenticated/expenses/$expenseId/route'
import { Route as AuthenticatedCompaniesCompanyIdRouteRouteImport } from './routes/_authenticated/companies/$companyId/route'
import { Route as AuthenticatedCarsCarIdRouteRouteImport } from './routes/_authenticated/cars/$carId/route'
import { Route as AuthenticatedPartsPartIdIndexRouteImport } from './routes/_authenticated/parts/$partId/index'
import { Route as AuthenticatedInspectionsInspectionIdIndexRouteImport } from './routes/_authenticated/inspections/$inspectionId/index'
import { Route as AuthenticatedExpensesExpenseIdIndexRouteImport } from './routes/_authenticated/expenses/$expenseId/index'
import { Route as AuthenticatedCompaniesCompanyIdIndexRouteImport } from './routes/_authenticated/companies/$companyId/index'
import { Route as AuthenticatedCarsCarIdIndexRouteImport } from './routes/_authenticated/cars/$carId/index'
import { Route as AuthenticatedPartsPartIdEditRouteImport } from './routes/_authenticated/parts/$partId/edit'
import { Route as AuthenticatedInspectionsInspectionIdEditRouteImport } from './routes/_authenticated/inspections/$inspectionId/edit'
import { Route as AuthenticatedExpensesExpenseIdEditRouteImport } from './routes/_authenticated/expenses/$expenseId/edit'
import { Route as AuthenticatedCompaniesCompanyIdEditRouteImport } from './routes/_authenticated/companies/$companyId/edit'
import { Route as AuthenticatedCarsCarIdEditRouteImport } from './routes/_authenticated/cars/$carId/edit'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartsRouteRoute = AuthenticatedPartsRouteRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInspectionsRouteRoute =
  AuthenticatedInspectionsRouteRouteImport.update({
    id: '/inspections',
    path: '/inspections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesRouteRoute =
  AuthenticatedExpensesRouteRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesRouteRoute =
  AuthenticatedCompaniesRouteRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarsRouteRoute = AuthenticatedCarsRouteRouteImport.update({
  id: '/cars',
  path: '/cars',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPartsIndexRoute = AuthenticatedPartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedPartsRouteRoute,
} as any)
const AuthenticatedInspectionsIndexRoute =
  AuthenticatedInspectionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectionsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpensesIndexRoute =
  AuthenticatedExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCarsRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPartsNewRoute = AuthenticatedPartsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedPartsRouteRoute,
} as any)
const AuthenticatedInspectionsNewRoute =
  AuthenticatedInspectionsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedInspectionsRouteRoute,
  } as any)
const AuthenticatedExpensesNewRoute =
  AuthenticatedExpensesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompaniesNewRoute =
  AuthenticatedCompaniesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCompaniesRouteRoute,
  } as any)
const AuthenticatedCarsNewRoute = AuthenticatedCarsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCarsRouteRoute,
} as any)
const AuthenticatedPartsPartIdRouteRoute =
  AuthenticatedPartsPartIdRouteRouteImport.update({
    id: '/$partId',
    path: '/$partId',
    getParentRoute: () => AuthenticatedPartsRouteRoute,
  } as any)
const AuthenticatedInspectionsInspectionIdRouteRoute =
  AuthenticatedInspectionsInspectionIdRouteRouteImport.update({
    id: '/$inspectionId',
    path: '/$inspectionId',
    getParentRoute: () => AuthenticatedInspectionsRouteRoute,
  } as any)
const AuthenticatedExpensesExpenseIdRouteRoute =
  AuthenticatedExpensesExpenseIdRouteRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => AuthenticatedExpensesRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRouteRoute =
  AuthenticatedCompaniesCompanyIdRouteRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedCompaniesRouteRoute,
  } as any)
const AuthenticatedCarsCarIdRouteRoute =
  AuthenticatedCarsCarIdRouteRouteImport.update({
    id: '/$carId',
    path: '/$carId',
    getParentRoute: () => AuthenticatedCarsRouteRoute,
  } as any)
const AuthenticatedPartsPartIdIndexRoute =
  AuthenticatedPartsPartIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPartsPartIdRouteRoute,
  } as any)
const AuthenticatedInspectionsInspectionIdIndexRoute =
  AuthenticatedInspectionsInspectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInspectionsInspectionIdRouteRoute,
  } as any)
const AuthenticatedExpensesExpenseIdIndexRoute =
  AuthenticatedExpensesExpenseIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedExpensesExpenseIdRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdIndexRoute =
  AuthenticatedCompaniesCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRouteRoute,
  } as any)
const AuthenticatedCarsCarIdIndexRoute =
  AuthenticatedCarsCarIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarsCarIdRouteRoute,
  } as any)
const AuthenticatedPartsPartIdEditRoute =
  AuthenticatedPartsPartIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedPartsPartIdRouteRoute,
  } as any)
const AuthenticatedInspectionsInspectionIdEditRoute =
  AuthenticatedInspectionsInspectionIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedInspectionsInspectionIdRouteRoute,
  } as any)
const AuthenticatedExpensesExpenseIdEditRoute =
  AuthenticatedExpensesExpenseIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedExpensesExpenseIdRouteRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdEditRoute =
  AuthenticatedCompaniesCompanyIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedCompaniesCompanyIdRouteRoute,
  } as any)
const AuthenticatedCarsCarIdEditRoute =
  AuthenticatedCarsCarIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedCarsCarIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/cars': typeof AuthenticatedCarsRouteRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteRouteWithChildren
  '/expenses': typeof AuthenticatedExpensesRouteRouteWithChildren
  '/inspections': typeof AuthenticatedInspectionsRouteRouteWithChildren
  '/parts': typeof AuthenticatedPartsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/cars/$carId': typeof AuthenticatedCarsCarIdRouteRouteWithChildren
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteRouteWithChildren
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  '/inspections/$inspectionId': typeof AuthenticatedInspectionsInspectionIdRouteRouteWithChildren
  '/parts/$partId': typeof AuthenticatedPartsPartIdRouteRouteWithChildren
  '/cars/new': typeof AuthenticatedCarsNewRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/parts/': typeof AuthenticatedPartsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/companies/$companyId/edit': typeof AuthenticatedCompaniesCompanyIdEditRoute
  '/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/inspections/$inspectionId/edit': typeof AuthenticatedInspectionsInspectionIdEditRoute
  '/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
  '/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/expenses/$expenseId/': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/inspections/$inspectionId/': typeof AuthenticatedInspectionsInspectionIdIndexRoute
  '/parts/$partId/': typeof AuthenticatedPartsPartIdIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/cars/new': typeof AuthenticatedCarsNewRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/parts/new': typeof AuthenticatedPartsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/inspections': typeof AuthenticatedInspectionsIndexRoute
  '/parts': typeof AuthenticatedPartsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/companies/$companyId/edit': typeof AuthenticatedCompaniesCompanyIdEditRoute
  '/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/inspections/$inspectionId/edit': typeof AuthenticatedInspectionsInspectionIdEditRoute
  '/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdIndexRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/inspections/$inspectionId': typeof AuthenticatedInspectionsInspectionIdIndexRoute
  '/parts/$partId': typeof AuthenticatedPartsPartIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/cars': typeof AuthenticatedCarsRouteRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteRouteWithChildren
  '/_authenticated/expenses': typeof AuthenticatedExpensesRouteRouteWithChildren
  '/_authenticated/inspections': typeof AuthenticatedInspectionsRouteRouteWithChildren
  '/_authenticated/parts': typeof AuthenticatedPartsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cars/$carId': typeof AuthenticatedCarsCarIdRouteRouteWithChildren
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRouteRouteWithChildren
  '/_authenticated/expenses/$expenseId': typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  '/_authenticated/inspections/$inspectionId': typeof AuthenticatedInspectionsInspectionIdRouteRouteWithChildren
  '/_authenticated/parts/$partId': typeof AuthenticatedPartsPartIdRouteRouteWithChildren
  '/_authenticated/cars/new': typeof AuthenticatedCarsNewRoute
  '/_authenticated/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/inspections/new': typeof AuthenticatedInspectionsNewRoute
  '/_authenticated/parts/new': typeof AuthenticatedPartsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/inspections/': typeof AuthenticatedInspectionsIndexRoute
  '/_authenticated/parts/': typeof AuthenticatedPartsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/cars/$carId/edit': typeof AuthenticatedCarsCarIdEditRoute
  '/_authenticated/companies/$companyId/edit': typeof AuthenticatedCompaniesCompanyIdEditRoute
  '/_authenticated/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/_authenticated/inspections/$inspectionId/edit': typeof AuthenticatedInspectionsInspectionIdEditRoute
  '/_authenticated/parts/$partId/edit': typeof AuthenticatedPartsPartIdEditRoute
  '/_authenticated/cars/$carId/': typeof AuthenticatedCarsCarIdIndexRoute
  '/_authenticated/companies/$companyId/': typeof AuthenticatedCompaniesCompanyIdIndexRoute
  '/_authenticated/expenses/$expenseId/': typeof AuthenticatedExpensesExpenseIdIndexRoute
  '/_authenticated/inspections/$inspectionId/': typeof AuthenticatedInspectionsInspectionIdIndexRoute
  '/_authenticated/parts/$partId/': typeof AuthenticatedPartsPartIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/cars'
    | '/companies'
    | '/expenses'
    | '/inspections'
    | '/parts'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/cars/$carId'
    | '/companies/$companyId'
    | '/expenses/$expenseId'
    | '/inspections/$inspectionId'
    | '/parts/$partId'
    | '/cars/new'
    | '/companies/new'
    | '/errors/$error'
    | '/expenses/new'
    | '/inspections/new'
    | '/parts/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/cars/'
    | '/chats/'
    | '/companies/'
    | '/expenses/'
    | '/help-center/'
    | '/inspections/'
    | '/parts/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/cars/$carId/edit'
    | '/companies/$companyId/edit'
    | '/expenses/$expenseId/edit'
    | '/inspections/$inspectionId/edit'
    | '/parts/$partId/edit'
    | '/cars/$carId/'
    | '/companies/$companyId/'
    | '/expenses/$expenseId/'
    | '/inspections/$inspectionId/'
    | '/parts/$partId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/cars/new'
    | '/companies/new'
    | '/errors/$error'
    | '/expenses/new'
    | '/inspections/new'
    | '/parts/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/cars'
    | '/chats'
    | '/companies'
    | '/expenses'
    | '/help-center'
    | '/inspections'
    | '/parts'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/cars/$carId/edit'
    | '/companies/$companyId/edit'
    | '/expenses/$expenseId/edit'
    | '/inspections/$inspectionId/edit'
    | '/parts/$partId/edit'
    | '/cars/$carId'
    | '/companies/$companyId'
    | '/expenses/$expenseId'
    | '/inspections/$inspectionId'
    | '/parts/$partId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/cars'
    | '/_authenticated/companies'
    | '/_authenticated/expenses'
    | '/_authenticated/inspections'
    | '/_authenticated/parts'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/cars/$carId'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/expenses/$expenseId'
    | '/_authenticated/inspections/$inspectionId'
    | '/_authenticated/parts/$partId'
    | '/_authenticated/cars/new'
    | '/_authenticated/companies/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/expenses/new'
    | '/_authenticated/inspections/new'
    | '/_authenticated/parts/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/cars/'
    | '/_authenticated/chats/'
    | '/_authenticated/companies/'
    | '/_authenticated/expenses/'
    | '/_authenticated/help-center/'
    | '/_authenticated/inspections/'
    | '/_authenticated/parts/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/cars/$carId/edit'
    | '/_authenticated/companies/$companyId/edit'
    | '/_authenticated/expenses/$expenseId/edit'
    | '/_authenticated/inspections/$inspectionId/edit'
    | '/_authenticated/parts/$partId/edit'
    | '/_authenticated/cars/$carId/'
    | '/_authenticated/companies/$companyId/'
    | '/_authenticated/expenses/$expenseId/'
    | '/_authenticated/inspections/$inspectionId/'
    | '/_authenticated/parts/$partId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parts': {
      id: '/_authenticated/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof AuthenticatedPartsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspections': {
      id: '/_authenticated/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof AuthenticatedInspectionsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars': {
      id: '/_authenticated/cars'
      path: '/cars'
      fullPath: '/cars'
      preLoaderRoute: typeof AuthenticatedCarsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/parts/': {
      id: '/_authenticated/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof AuthenticatedPartsIndexRouteImport
      parentRoute: typeof AuthenticatedPartsRouteRoute
    }
    '/_authenticated/inspections/': {
      id: '/_authenticated/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof AuthenticatedInspectionsIndexRouteImport
      parentRoute: typeof AuthenticatedInspectionsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AuthenticatedExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedCarsRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/parts/new': {
      id: '/_authenticated/parts/new'
      path: '/new'
      fullPath: '/parts/new'
      preLoaderRoute: typeof AuthenticatedPartsNewRouteImport
      parentRoute: typeof AuthenticatedPartsRouteRoute
    }
    '/_authenticated/inspections/new': {
      id: '/_authenticated/inspections/new'
      path: '/new'
      fullPath: '/inspections/new'
      preLoaderRoute: typeof AuthenticatedInspectionsNewRouteImport
      parentRoute: typeof AuthenticatedInspectionsRouteRoute
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/companies/new': {
      id: '/_authenticated/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof AuthenticatedCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedCompaniesRouteRoute
    }
    '/_authenticated/cars/new': {
      id: '/_authenticated/cars/new'
      path: '/new'
      fullPath: '/cars/new'
      preLoaderRoute: typeof AuthenticatedCarsNewRouteImport
      parentRoute: typeof AuthenticatedCarsRouteRoute
    }
    '/_authenticated/parts/$partId': {
      id: '/_authenticated/parts/$partId'
      path: '/$partId'
      fullPath: '/parts/$partId'
      preLoaderRoute: typeof AuthenticatedPartsPartIdRouteRouteImport
      parentRoute: typeof AuthenticatedPartsRouteRoute
    }
    '/_authenticated/inspections/$inspectionId': {
      id: '/_authenticated/inspections/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/inspections/$inspectionId'
      preLoaderRoute: typeof AuthenticatedInspectionsInspectionIdRouteRouteImport
      parentRoute: typeof AuthenticatedInspectionsRouteRoute
    }
    '/_authenticated/expenses/$expenseId': {
      id: '/_authenticated/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdRouteRouteImport
      parentRoute: typeof AuthenticatedExpensesRouteRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteRouteImport
      parentRoute: typeof AuthenticatedCompaniesRouteRoute
    }
    '/_authenticated/cars/$carId': {
      id: '/_authenticated/cars/$carId'
      path: '/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthenticatedCarsCarIdRouteRouteImport
      parentRoute: typeof AuthenticatedCarsRouteRoute
    }
    '/_authenticated/parts/$partId/': {
      id: '/_authenticated/parts/$partId/'
      path: '/'
      fullPath: '/parts/$partId/'
      preLoaderRoute: typeof AuthenticatedPartsPartIdIndexRouteImport
      parentRoute: typeof AuthenticatedPartsPartIdRouteRoute
    }
    '/_authenticated/inspections/$inspectionId/': {
      id: '/_authenticated/inspections/$inspectionId/'
      path: '/'
      fullPath: '/inspections/$inspectionId/'
      preLoaderRoute: typeof AuthenticatedInspectionsInspectionIdIndexRouteImport
      parentRoute: typeof AuthenticatedInspectionsInspectionIdRouteRoute
    }
    '/_authenticated/expenses/$expenseId/': {
      id: '/_authenticated/expenses/$expenseId/'
      path: '/'
      fullPath: '/expenses/$expenseId/'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdIndexRouteImport
      parentRoute: typeof AuthenticatedExpensesExpenseIdRouteRoute
    }
    '/_authenticated/companies/$companyId/': {
      id: '/_authenticated/companies/$companyId/'
      path: '/'
      fullPath: '/companies/$companyId/'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRouteRoute
    }
    '/_authenticated/cars/$carId/': {
      id: '/_authenticated/cars/$carId/'
      path: '/'
      fullPath: '/cars/$carId/'
      preLoaderRoute: typeof AuthenticatedCarsCarIdIndexRouteImport
      parentRoute: typeof AuthenticatedCarsCarIdRouteRoute
    }
    '/_authenticated/parts/$partId/edit': {
      id: '/_authenticated/parts/$partId/edit'
      path: '/edit'
      fullPath: '/parts/$partId/edit'
      preLoaderRoute: typeof AuthenticatedPartsPartIdEditRouteImport
      parentRoute: typeof AuthenticatedPartsPartIdRouteRoute
    }
    '/_authenticated/inspections/$inspectionId/edit': {
      id: '/_authenticated/inspections/$inspectionId/edit'
      path: '/edit'
      fullPath: '/inspections/$inspectionId/edit'
      preLoaderRoute: typeof AuthenticatedInspectionsInspectionIdEditRouteImport
      parentRoute: typeof AuthenticatedInspectionsInspectionIdRouteRoute
    }
    '/_authenticated/expenses/$expenseId/edit': {
      id: '/_authenticated/expenses/$expenseId/edit'
      path: '/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdEditRouteImport
      parentRoute: typeof AuthenticatedExpensesExpenseIdRouteRoute
    }
    '/_authenticated/companies/$companyId/edit': {
      id: '/_authenticated/companies/$companyId/edit'
      path: '/edit'
      fullPath: '/companies/$companyId/edit'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdEditRouteImport
      parentRoute: typeof AuthenticatedCompaniesCompanyIdRouteRoute
    }
    '/_authenticated/cars/$carId/edit': {
      id: '/_authenticated/cars/$carId/edit'
      path: '/edit'
      fullPath: '/cars/$carId/edit'
      preLoaderRoute: typeof AuthenticatedCarsCarIdEditRouteImport
      parentRoute: typeof AuthenticatedCarsCarIdRouteRoute
    }
  }
}

interface AuthenticatedCarsCarIdRouteRouteChildren {
  AuthenticatedCarsCarIdEditRoute: typeof AuthenticatedCarsCarIdEditRoute
  AuthenticatedCarsCarIdIndexRoute: typeof AuthenticatedCarsCarIdIndexRoute
}

const AuthenticatedCarsCarIdRouteRouteChildren: AuthenticatedCarsCarIdRouteRouteChildren =
  {
    AuthenticatedCarsCarIdEditRoute: AuthenticatedCarsCarIdEditRoute,
    AuthenticatedCarsCarIdIndexRoute: AuthenticatedCarsCarIdIndexRoute,
  }

const AuthenticatedCarsCarIdRouteRouteWithChildren =
  AuthenticatedCarsCarIdRouteRoute._addFileChildren(
    AuthenticatedCarsCarIdRouteRouteChildren,
  )

interface AuthenticatedCarsRouteRouteChildren {
  AuthenticatedCarsCarIdRouteRoute: typeof AuthenticatedCarsCarIdRouteRouteWithChildren
  AuthenticatedCarsNewRoute: typeof AuthenticatedCarsNewRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
}

const AuthenticatedCarsRouteRouteChildren: AuthenticatedCarsRouteRouteChildren =
  {
    AuthenticatedCarsCarIdRouteRoute:
      AuthenticatedCarsCarIdRouteRouteWithChildren,
    AuthenticatedCarsNewRoute: AuthenticatedCarsNewRoute,
    AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
  }

const AuthenticatedCarsRouteRouteWithChildren =
  AuthenticatedCarsRouteRoute._addFileChildren(
    AuthenticatedCarsRouteRouteChildren,
  )

interface AuthenticatedCompaniesCompanyIdRouteRouteChildren {
  AuthenticatedCompaniesCompanyIdEditRoute: typeof AuthenticatedCompaniesCompanyIdEditRoute
  AuthenticatedCompaniesCompanyIdIndexRoute: typeof AuthenticatedCompaniesCompanyIdIndexRoute
}

const AuthenticatedCompaniesCompanyIdRouteRouteChildren: AuthenticatedCompaniesCompanyIdRouteRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdEditRoute:
      AuthenticatedCompaniesCompanyIdEditRoute,
    AuthenticatedCompaniesCompanyIdIndexRoute:
      AuthenticatedCompaniesCompanyIdIndexRoute,
  }

const AuthenticatedCompaniesCompanyIdRouteRouteWithChildren =
  AuthenticatedCompaniesCompanyIdRouteRoute._addFileChildren(
    AuthenticatedCompaniesCompanyIdRouteRouteChildren,
  )

interface AuthenticatedCompaniesRouteRouteChildren {
  AuthenticatedCompaniesCompanyIdRouteRoute: typeof AuthenticatedCompaniesCompanyIdRouteRouteWithChildren
  AuthenticatedCompaniesNewRoute: typeof AuthenticatedCompaniesNewRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
}

const AuthenticatedCompaniesRouteRouteChildren: AuthenticatedCompaniesRouteRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdRouteRoute:
      AuthenticatedCompaniesCompanyIdRouteRouteWithChildren,
    AuthenticatedCompaniesNewRoute: AuthenticatedCompaniesNewRoute,
    AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  }

const AuthenticatedCompaniesRouteRouteWithChildren =
  AuthenticatedCompaniesRouteRoute._addFileChildren(
    AuthenticatedCompaniesRouteRouteChildren,
  )

interface AuthenticatedExpensesExpenseIdRouteRouteChildren {
  AuthenticatedExpensesExpenseIdEditRoute: typeof AuthenticatedExpensesExpenseIdEditRoute
  AuthenticatedExpensesExpenseIdIndexRoute: typeof AuthenticatedExpensesExpenseIdIndexRoute
}

const AuthenticatedExpensesExpenseIdRouteRouteChildren: AuthenticatedExpensesExpenseIdRouteRouteChildren =
  {
    AuthenticatedExpensesExpenseIdEditRoute:
      AuthenticatedExpensesExpenseIdEditRoute,
    AuthenticatedExpensesExpenseIdIndexRoute:
      AuthenticatedExpensesExpenseIdIndexRoute,
  }

const AuthenticatedExpensesExpenseIdRouteRouteWithChildren =
  AuthenticatedExpensesExpenseIdRouteRoute._addFileChildren(
    AuthenticatedExpensesExpenseIdRouteRouteChildren,
  )

interface AuthenticatedExpensesRouteRouteChildren {
  AuthenticatedExpensesExpenseIdRouteRoute: typeof AuthenticatedExpensesExpenseIdRouteRouteWithChildren
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
}

const AuthenticatedExpensesRouteRouteChildren: AuthenticatedExpensesRouteRouteChildren =
  {
    AuthenticatedExpensesExpenseIdRouteRoute:
      AuthenticatedExpensesExpenseIdRouteRouteWithChildren,
    AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
    AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  }

const AuthenticatedExpensesRouteRouteWithChildren =
  AuthenticatedExpensesRouteRoute._addFileChildren(
    AuthenticatedExpensesRouteRouteChildren,
  )

interface AuthenticatedInspectionsInspectionIdRouteRouteChildren {
  AuthenticatedInspectionsInspectionIdEditRoute: typeof AuthenticatedInspectionsInspectionIdEditRoute
  AuthenticatedInspectionsInspectionIdIndexRoute: typeof AuthenticatedInspectionsInspectionIdIndexRoute
}

const AuthenticatedInspectionsInspectionIdRouteRouteChildren: AuthenticatedInspectionsInspectionIdRouteRouteChildren =
  {
    AuthenticatedInspectionsInspectionIdEditRoute:
      AuthenticatedInspectionsInspectionIdEditRoute,
    AuthenticatedInspectionsInspectionIdIndexRoute:
      AuthenticatedInspectionsInspectionIdIndexRoute,
  }

const AuthenticatedInspectionsInspectionIdRouteRouteWithChildren =
  AuthenticatedInspectionsInspectionIdRouteRoute._addFileChildren(
    AuthenticatedInspectionsInspectionIdRouteRouteChildren,
  )

interface AuthenticatedInspectionsRouteRouteChildren {
  AuthenticatedInspectionsInspectionIdRouteRoute: typeof AuthenticatedInspectionsInspectionIdRouteRouteWithChildren
  AuthenticatedInspectionsNewRoute: typeof AuthenticatedInspectionsNewRoute
  AuthenticatedInspectionsIndexRoute: typeof AuthenticatedInspectionsIndexRoute
}

const AuthenticatedInspectionsRouteRouteChildren: AuthenticatedInspectionsRouteRouteChildren =
  {
    AuthenticatedInspectionsInspectionIdRouteRoute:
      AuthenticatedInspectionsInspectionIdRouteRouteWithChildren,
    AuthenticatedInspectionsNewRoute: AuthenticatedInspectionsNewRoute,
    AuthenticatedInspectionsIndexRoute: AuthenticatedInspectionsIndexRoute,
  }

const AuthenticatedInspectionsRouteRouteWithChildren =
  AuthenticatedInspectionsRouteRoute._addFileChildren(
    AuthenticatedInspectionsRouteRouteChildren,
  )

interface AuthenticatedPartsPartIdRouteRouteChildren {
  AuthenticatedPartsPartIdEditRoute: typeof AuthenticatedPartsPartIdEditRoute
  AuthenticatedPartsPartIdIndexRoute: typeof AuthenticatedPartsPartIdIndexRoute
}

const AuthenticatedPartsPartIdRouteRouteChildren: AuthenticatedPartsPartIdRouteRouteChildren =
  {
    AuthenticatedPartsPartIdEditRoute: AuthenticatedPartsPartIdEditRoute,
    AuthenticatedPartsPartIdIndexRoute: AuthenticatedPartsPartIdIndexRoute,
  }

const AuthenticatedPartsPartIdRouteRouteWithChildren =
  AuthenticatedPartsPartIdRouteRoute._addFileChildren(
    AuthenticatedPartsPartIdRouteRouteChildren,
  )

interface AuthenticatedPartsRouteRouteChildren {
  AuthenticatedPartsPartIdRouteRoute: typeof AuthenticatedPartsPartIdRouteRouteWithChildren
  AuthenticatedPartsNewRoute: typeof AuthenticatedPartsNewRoute
  AuthenticatedPartsIndexRoute: typeof AuthenticatedPartsIndexRoute
}

const AuthenticatedPartsRouteRouteChildren: AuthenticatedPartsRouteRouteChildren =
  {
    AuthenticatedPartsPartIdRouteRoute:
      AuthenticatedPartsPartIdRouteRouteWithChildren,
    AuthenticatedPartsNewRoute: AuthenticatedPartsNewRoute,
    AuthenticatedPartsIndexRoute: AuthenticatedPartsIndexRoute,
  }

const AuthenticatedPartsRouteRouteWithChildren =
  AuthenticatedPartsRouteRoute._addFileChildren(
    AuthenticatedPartsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarsRouteRoute: typeof AuthenticatedCarsRouteRouteWithChildren
  AuthenticatedCompaniesRouteRoute: typeof AuthenticatedCompaniesRouteRouteWithChildren
  AuthenticatedExpensesRouteRoute: typeof AuthenticatedExpensesRouteRouteWithChildren
  AuthenticatedInspectionsRouteRoute: typeof AuthenticatedInspectionsRouteRouteWithChildren
  AuthenticatedPartsRouteRoute: typeof AuthenticatedPartsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarsRouteRoute: AuthenticatedCarsRouteRouteWithChildren,
  AuthenticatedCompaniesRouteRoute:
    AuthenticatedCompaniesRouteRouteWithChildren,
  AuthenticatedExpensesRouteRoute: AuthenticatedExpensesRouteRouteWithChildren,
  AuthenticatedInspectionsRouteRoute:
    AuthenticatedInspectionsRouteRouteWithChildren,
  AuthenticatedPartsRouteRoute: AuthenticatedPartsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
